#!/usr/bin/env bash
# Displays information about subdomains

print_sd_info() {
	if [ -z $2 ]; then
		dig "www.$1" | awk '$4=="A" {print "The subdomain www is a " $4 " record and points to " $5}'
		dig "lb-01.$1" | awk '$4=="A" {print "The subdomain lb-01 is a " $4 " record and points to " $5}'
		dig "web-01.$1" | awk '$4=="A" {print "The subdomain web-01 is a " $4 " record and points to " $5}'
		dig "web-02.$1" | awk '$4=="A" {print "The subdomain web-02 is a " $4 " record and points to " $5}'
	else
		dig "$2.$1" | awk -v SUB_DOMAIN="$2" '$4=="A" {print "The subdomain " SUB_DOMAIN " is a " $4 " record and points to " $5}'
	fi
}

print_sd_info $1 $2
