#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update;
apt-get install nginx;
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html;
sed -i "s/server_name _;/server_name _;\n\terror_page 404 \/custom_404.html;/" /etc/nginx/sites-available/default;
service nginx restart
