#!/usr/bin/env bash
# Configuring nginx on a new system to have a response header X-served_by
# x-served_by: {hostname}

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'NGINX HTTP'
HOST="$(hostname)"
sudo sed -i "/server_name/a\\\tadd_header X-Served-By $HOST;" /etc/nginx/sites-available/default
sudo service nginx restart
