#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo echo -e "
frontend test_proxy
\tbind *:80
\tdefault_backend proxy_backend\n
backend proxy_backend
\tbalance roundrobin
\tserver web-01 52.87.215.141
\tserver web-02 54.174.134.107" >> /etc/haproxy/haproxy.cfg
sudo /etc/init.d/haproxy reload
sudo /etc/init.d/haproxy restart
