#!/usr/bin/env bash
# Bash script that solves a problem of nginx not listening to port 80

apt-get update
apt-get -y install nginx
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
service nginx restart
