#!/usr/bin/env bash
# Bash script that solves a problem of nginx not listening to port 80

rm /etc/nginx/sites-enabled/default/
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
