#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
while IFS=: read -r USERNAME PASSWD USERID GROUPID USERINFO HOME_DIRECTORY SH; do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOME_DIRECTORY and rides $SH. $USERID's place is protected by the passcode $PASSWD, more info about the user here: $USERINFO"
done < etc-passwd #/etc/passwd
