#!/usr/bin/env bash
# This script tells you Best school ten times
#-------- SCRIPT -------
i=1
while [ $i -lt 21 ] 
do
	echo "$i"
	if [ $i -eq 4 ]; then
		echo "bad luck from china"
	elif [ $i -eq 9 ]; then
		echo "bad luck from japan"
	elif [ $i -eq 17 ]; then
		echo "bad luck from italy"
	fi
	let i++
done
