#!/usr/bin/env bash
#Bash script that displays Best School 10 times.

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
			;;
		*)
			echo $i
	esac
	((i++))
done
