#!/usr/bin/env bash
#Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for f in `ls` ; do
	echo $f | cut -f 1 --complement -d "-"
done
