#!/usr/bin/env bash
# Get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.

apt install -y apache2
mkdir -p /usr/local/apache2/htdocs
echo 'Hello Holberton' > /usr/local/apache2/htdocs/index.html
