#!/usr/bin/env bash
# Get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.

apt install -y docker
echo "
	FROM httpd
	RUN mkdir -p /usr/local/apache2/htdocs && \
	echo 'Hello Holberton' > /usr/local/apache2/htdocs/index.html
	EXPOSE 80
	" > dockerfile
docker build -t schooltask .
docker run -p 8080:80 -d -it schooltask
