#!/usr/bin/env bash
# fix nginx to run as nginx user on container
pkill apache2
chown -R nginx:nginx /var/{log,lib}/nginx
chmod 644 /etc/nginx/nginx.conf
sed -i "s/listen [0-9]\{1,10\}/listen 8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
