#!/usr/bin/env bash
# fix nginx to run as nginx user on container
apt-get -y install nginx
chown -R nginx:nginx /var/{log,lib}/nginx
sed -i "s/#user [a-zA-Z0-9_#-]\{1,10\}/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx nginx
